### PR TITLE
Improvements for AdminPanel on mobile

### PR DESCRIPTION
**Pull request by notcarbide**
I have made the following changes to primarily improve readability of forms and buttons on mobile devices.

- Reduce text in warning by encouraging backups
- Separate divs for forms with buttons so text is readable on mobile

With the following bugfix, should you want to simply fix the active nav tab:
- Initialize "active" tab properly for nav-tabs (nav-link vs nav-item)

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
@robiso This PR is a striking example of single huge lines creating unreadable diffs. Here, it is very difficult to see what has been actually changed! A 1341 characters line is waaaaaay too long! And it makes modifying it a real PITA.

I hope one day we can move the html out of the PHP code in templates ;)

Note: it shouldn't cause any issue to split the lines here!

**Comment by robiso** [comment]
@notcarbide, the first change (active tab on setting) kind of breaks the current functionality if the user is using Bootstrap 3 (which will be still the default one used in the WonderCMS 3.0.0 version.
Example for this behaviour:
two-active-tabs

What I've made in my previous pull request is, a functional active tab experience. If the user uses Bootstrap 4, he will run into this issue, but at least it wont be broken by default.
I suggest we leave it as it was, until we fully migrate to Bootstrap 4 in the future. So for now, let's stay with Bootstrap 3 and some Bootstrap 4 compatibility.

The other mobile changes also introduce a couple of issues when using Bootstrap 3, as seen in the screenshots below:
change-password-action
file-upload-button
upload-button


@NicolasCARPi, you are correct and I couldn't agree more, this was a bit frustrating, to say the least. :)
> Note: it shouldn't cause any issue to split the lines here!

Do you mean split the HTML lines into readable code? (Ala prettify?)

**Comment by NicolasCARPi** [comment]
> Do you mean split the HTML lines into readable code? (Ala prettify?)

Yes, it won't change a thing!

**Comment by notcarbide** [comment]
@robiso gotcha! Gonna close this pending prettifying things, I'll see what I can do to get a fix for mobile that won't break older bootstrap afterward.

**Comment by robiso** [comment]
@NicolasCARPi, will do this in the following pull request. I've nearly finished the screenshots for themes and plugins.

@notcarbide, thank you!

**Pull request closed without merging**
