### PR TITLE
Password (hash) Disclosure (closed and fix pushed)

### PR DESCRIPTION
**Pull request by yassineaddi**
Due to the bad stripping and conditioning, again there is a password disclosure with multiple ways:
https://wondercms.com/demo/pass<word
https://wondercms.com/demo/p\assword
https://wondercms.com/demo/pass=word
...etc

So, I came across the best solution as I said earlier to do the checks on the requested page itself AFTER the stripping ...etc
I discovered many other errors and bad practices but I can't find time to push all of them.

I think the best solution is to use the version I built:
https://github.com/yassineaddi/wondercms

I built it with security in mind, all the vuls are patched and tested all of them. It's OOP which means easy to build plugins over it ...etc and better for developers who wants to use it as a skeleton. Please take a few minutes to test it.

I highly suggest to use it instead and implement the new features over it which is very easy and I'm here of help if needed.

### CODE REVIEW

**Comment by robiso** [comment]
To add, I have tested your version numerous times and love it, but like I said, I'd love to see a cleaner version atleast of the themes section, and adding the WYSIWYG as a plugin, not included (as it makes WonderCMS go from a couple of kB to almost 400kB.

Can we somehow work together on this, to make it work with the latest version (0.9.9, which has extra settings and is completely responsive?

**Comment by yassineaddi** [comment]
Hi again,

In case of theming (layout.php), yes I messed up I was hurry, anyway, as you said I will separate it and make things a lot easier for the user to use. Also I will delete the Trumbowyg editor and make it a plugin as you mentioned.

About the vulnerability, the fix I submitted works, I just forgot to transform the $rp variable to lowercase. So the code will be:
`
if (strtolower($rp) == 'password') {
    $wCMS->requestedPage = '404';
}
`
And you can delete the following code as it's useless and can't handle all cases:
`
if (strpos(strtolower($_SERVER['REQUEST_URI']), 'password') !== false)  {
	header('Location: ./');
	exit;
}
`

We can work together, I will make the changes to the version I built and add Bootstrap framework so that it will be responsive ...etc

**Comment by robiso** [comment]
Thank you for your time and contribution. I would love to colaborate with you on this one. How fast do you think we can manage this. Should I push a fix first, and a new version, or can we work fast enough to make this happen overnight? What you mentioned is perfect in what I had in mind.

Here's a snippet for the bootstrap for the navigation and admin panel (doesn't include delete functionality yet, or meta and seo description for each page, or different login URL or different default homepage, there are just placeholders for now to make it easier to work with)

`<?php if (WonderCMS::$loggedIn): ?>
<div id='adminPanel' class='container-fluid'>
	<div class='padding20 toggle text-center' data-toggle='collapse' data-target='#settings'>&#9776;</div>
	<div class='col-xs-12 col-sm-8 col-sm-offset-2'>
		<div id='settings' class='collapse text-left'>
			<a href='?delete=" . $wCMS->config->currentPage . "' class='btn btn-danger' onclick='return confirm(\"Really delete page?\");' type='button'>Delete current page (".$wCMS->config->currentPage.")</a><div class='marginTop20'></div>
				<div class='form-group'><select class='form-control' name='themeSelect' onchange='fieldSave(\"themeSelect\",this.value);'>";
					<?php foreach (glob(ROOT.DS.'themes'.DS.'*', GLOB_ONLYDIR) as $dir): ?>
						<?php $dir = basename($dir); ?>
						<option value="<?php echo $dir; ?>"<?php echo (WonderCMS::get('theme') == $dir) ? ' selected' : null; ?>><?php echo $dir; ?></option>
					<?php endforeach; ?>
				</select></div>
			<?php foreach (['description', 'keywords', 'title', 'copyright'] as $key): ?>
				<div class="change">
					<span id="<?php echo $key; ?>" class="editText"><?php echo WonderCMS::get($key); ?></span>
				</div>
			<?php endforeach; ?>


			<div class='change marginTop20'>
				<b style='font-size: 22px; text-align: right' class='glyphicon glyphicon-info-sign' aria-hidden='true' data-toggle='tooltip' data-placement='right' title='Menu: enter a new page name in a new line.'></b>
				<span id="menuItems" class="editText"><?php echo str_replace("\n", "<br>", WonderCMS::get('menuItems')); ?></span>
			</div>
			<div class='change'>
				<b style='font-size: 22px;' class='glyphicon glyphicon-info-sign' aria-hidden='true' data-toggle='tooltip' data-placement='right' title='Default homepage: to make another page your default homepage, rename this to another existing page.'></b>
				<span id='page' class='editText'>" . $wCMS->config->page . "</span>
			</div>
			<div class='change'>
				<span id='loginURL' class='editText'>" . $wCMS->config->loginURL . "</span>
				<br />Current login URL (once you change it, bookmark it):<br />http:" . $wCMS->host . "?<b>" . $wCMS->config->loginURL . "</b>
			</div>
			<div class='change grayFont marginTop20'>
					<div class='form-group'><input class='form-control' type="password" id="password" placeholder='New password'></div>
					<button class='btn btn-info' type='submit' id="changePassword">Change password</button>
			</div>
			<div class='padding20 toggle text-center' data-toggle='collapse' data-target='#settings'>Close settings</div>
		</div>
	</div>
</div>
<?php endif; ?>`

Can we communicate through any other channel to make the communcation faster?

**Comment by yassineaddi** [comment]
I prefer to push the fix first.
I will start working on it and let you know once finish it. I will need your email, skype, facebook... so that I can contact you and ask for further information if there are any.
Here is my fb: https://www.facebook.com/yassine.addi.tgh
My skype is: yassineaddi

**Comment by robiso** [comment]
Pushed fix and added you on Skype.

**Comment by yassineaddi** [comment]
Sorry I made mistake, skype ID: yassineaddi.dev

**Comment by robiso** [comment]
Tried a search and no skype id could be found for: yassineaddi.dev

**Comment by yassineaddi** [comment]
Oh, I use web version of skype cause I'm on linux, it has some problems. Anyway, you can contact me via facebook, the profile is up.

**Comment by robiso** [comment]
Since I don't use FB, how about you add me on Skype?-> robert.isoski

**Comment by yassineaddi** [comment]
Ok added you.

**Pull request closed without merging**
