### PR TITLE
Added priorities for hooks.

### PR DESCRIPTION
**Pull request by nightillusions**
If there are more than one listener for a hook (e.g. more than one plugin), it is possible to rearrange the order with a priority.

Default priority = 10

### CODE REVIEW

**Comment by robiso** [comment]
Thank you for the contribution. Could this cause any conflicts with existing plugins, or do plugin author need to update anything?

**Comment by wdj-ac** [comment]
You´re welcome!
it only cause conflicts in Plugins which make use of the array $_listeners. 
All approved plugins doesn´t use this array, but I also tested them without conflicts. 
- [x] Summernote WYSIWYG 2.0.0 + file uploader 
- [x] Create new editable areas 2.0.0 
- [x] Contact form 2.0.0
- [x] MediumEditor WYSIWYG 1.0.0 
- [x] Hits counter 2.0.0

**Small hint:** 
In the "Contact Form Plugin" is a wrong part in the "How to". There stands, you have to use $_currentPage instead of $currentPage 

The only plugin I have found so far with a conflict, is "modern_settings" on line 230 in the _modern_settings.php:
```
if(($k = array_search('displayModernSettings', wCMS::$_listeners['settings'])) !== false) {
			unset(wCMS::$_listeners['settings'][$k]);
		}
```
could be changed to something like this to work well:
```
if(($k = array_search('displayModernSettings', wCMS::$_listeners['settings'][10])) !== false) {
			unset(wCMS::$_listeners['settings'][10][$k]);
		}
```

**Comment by robiso** [comment]
Thank you again for the excellent report.

When and if we apply this to upcoming version 2.03, we'll update the Contact plugin and change wCMS::$_currentPage to wCMS::$currentPage.

I have one more question, what happens if multiple hooks have the same priority? Which one loads first and could anything go wrong that you would know of?

I'll will also notify the modern settings plugin author, Prakai, to update his plugin we release WonderCMS 2.0.3 to make the update a flawless transition for everyone.

Please also notify us of your name/last name and possibly a website, so we can add you to wondercms.com/special-contributors.

Thanks!

**Comment by wdj-ac** [comment]
> What happens if multiple hooks have the same priority? Which one loads first and could anything go wrong that you would know of?

It is the same behavior as before. Multiple hooks with same priority => First come, first served.
The default priority value is 10 and every plugin without setting it, will be placed in the queue at the end. But if a hook needs to be processed earlier, a plugin developer could set a priority lower than the default value. 

I tested it to order menu items of plugins:
First Backup
First Gallery

> Please also notify us of your name/last name and possibly a website, so we can add you to wondercms.com/special-contributors.

Thanks! 
Pascal Jordin <http://jordin.eu>

**Comment by robiso** [comment]
Perfect. I'll accept this pull request before releasing 2.0.3 in the upcoming days, but we'll remove the comment out of it since we don't leave comments inside to keep WonderCMS as small as it gets. Thank you for the pretty code!

We'll add you when we add you, this will probably happen when the pull request is merged.

**Comment by robiso** [comment]
Hi @wdj-ac, happy new year!

Would you be interested in implementing plugin hook priorities in the latest 2.4.0 version?

Cheers!

**Comment by robiso** [comment]
Closing this pull request for now, let me know if anyone is interested in implementing this in the future

**Pull request closed without merging**
