### PR TITLE
Add custom exceptions

### PR DESCRIPTION
**Pull request by NicolasCARPi**
Now the code doesn't throw a generic Exception anymore (bad practice)
Add two custom exceptions: for filesystem related issues, and for
invalid token.
Also update the composer.lock and composer dependencies
Right now all exceptions are handled the same way, but this change at
least allows to handle them differently in the future.

You might think: but what could be the use of having different exceptions? Example: the invalid token exception might be logged as it might be a hacking attempt. As for the FilesystemError, maybe we just want to show the user a generic error message ("Something went wrong!"), but log a complete and more verbose error so the admin can see what went wrong. This prevent accidentally disclosing info to the attacker.

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
It's great to have Scrutinizer checking the code on the PR now :)

One other thing that might be interesting to have on the repo is this: https://cla-assistant.io/

It allows contributors to sign a waiver, so you can free yourself from the implications of having code from others in the repo. See example: https://cla-assistant.io/elabftw/elabftw?pullRequest=1085

It's a bunch of legal mumbo jumbo but it's good to have. Also, a bot will take care of asking users to sign it so it's minimal work once it's setup.

**Comment by robiso** [comment]
This is very neat and nice explanation.

**Comment by robiso** [comment]
I'll check the cla assistant tomorrow. Thanks!
Is there any way I can tell scrutinizer that this project is open source, or do they automagically know?

**Comment by NicolasCARPi** [comment]
They know.

**Comment by robiso** [comment]
> They know

Que Xfiles music. :)

Cla assistant merged into this repo, thanks for the recommendation.

**Pull request merged**
