### PR TITLE
Update Wcms.php (prettify settings function)

### PR DESCRIPTION
**Pull request by robiso**
Prettifying the settings, bringing more readability.

### CODE REVIEW

**Comment by robiso** [comment]
@NicolasCARPi, @notcarbide, seems nicer. And yes, I know, a separate file is necessary!

On another note, it seems odd some errors are displayed in a separate page. What the difference between the below two?

`throw new InvalidArgumentException('Invalid addon URL');`
and
`$this->alert('danger', 'Invalid addon URL');`

**Comment by NicolasCARPi** [comment]
throwing an exception will stop execution of the code and go directly to the catch statement, whereas alert() is just displaying errors stored in the session.

congrats on splitting the code, it looks much nicer like that! Now it can actually be worked on ;)

**Comment by robiso** [comment]
@NicolasCARPi, will you do the honor of squashing this one?

> throwing an exception will stop execution of the code and go directly to the catch statement, whereas alert() is just displaying errors stored in the session.

Do you see anything bad if I re-enable the alert for this case (the invalid addon URL)? This is the only one I would leave as an alert, all other exceptions seem fine. It would be a rare occasion any average user would see the other exception errors.

**Comment by NicolasCARPi** [comment]
Sure, do what you feel is right. If needed I'll make a PR if I believe it can be improved ;)

**Comment by robiso** [comment]
@NicolasCARPi, I'll squash and merge this then. :)

**Pull request merged**
