### PR TITLE
Move the class in its own file and other major changes

### PR DESCRIPTION
**Pull request by NicolasCARPi**
Ok, I'll try to summarize the changes I've made. Note that the code is NOT in a working state because of plugins (see the commented line in the init() function). The plugins will need to be updated. I just wanted to make the PR now, otherwise it'll be too big afterwards. No need to change everything in one go. Incremental changes are easier to deal with.

### Moving the Wcms class to its own file

PHP files should not declare symbols (like a class) and also execute logic with side effects. So I moved the Wcms class into `src/classes/Wcms.php`. This makes the index.php file much smaller, and only doing what it's supposed to do: init() and render().

Note that I've had to "globalize" the class instance into the other files in `themes` (instead of spawning a new instance), I'll work on that later (the `global` keyword should not be used in a properly architected software). I had to workaround the particularities of Wcms :)

### Removing all the static stuff

As a lot of users on Reddit told you, having all your methods static is not particularly a good idea. Now, the class needs to be instanciated (with the `new` keyword), and it has state. This has several advantages. For instance, when you instantiate it, it reads the database and stores it in a property (see the call to getDb() in the constructor). The property can be accessed by other functions (`$this->db`). This means that the database file is read only once per request -> improved performance. I've also cleaned up the function names and reorganized some things. Example: when calling "getDb()", if the database is not here, it creates it. Read the code, you'll see that most changes make the code flow more logical and better encapsulated: when calling getDb, I want the db, I don't care if it exists or not, I just want the db. It's the role of getDb to create it first if it doesn't exist, not the caller code.

### Fixing the private/public

A private method can only be called from within the class. A public method can be called by a template or a plugin. This also has the added benefit of providing insight to other devs on the purpose of the function. And when editing a private function, you can be sure that it will not break anything outside because it CANNOT be called from outside. This adds a sort of "interface" to the software, where external devs/plugins know what methods can be called. Of course a proper interface would be nice to have, maybe later. It would allow plugin developers to have some sort of guidance on what must be implemented.

### Misc

Right now there is still one single big class, as I didn't feel the need to split it. But in the future, it would be better to split it, to improve readability and maintainability. For instance, the backup stuff could move to its own class, as it's not really related to the rest of the software.

I think I broke the summernote stuff and maybe other things, please test on your side and report any issue. As I said, the code is not in a 100% working state, but one has to start somewhere. At least the basic functions are working afaik. And the backup is working as you requested: it backups the whole folder.

## Composer

Composer is now required to download PHP dependencies and put them in the `vendor` folder, that is not tracked by git. What this means is:

* for installation with git, users will need to install composer and run `composer install` before being able to use it
* for the zip install, you will need to have a script generating a zip with all the required files in there, and that's the zip that users will download and put on their server for an out-of-the-box experience. Basically, the script will just install composer and run `composer install`, and create a zip, nothing complicated to do. Maybe create a "wondercms-builder" repo and add me as contributor, I'll add the script.

Note that it would be nice also to remove the minified files (js and css) from git, to avoid them polluting the "git grep" command (very useful command), and also because git should only track source files, not "compiled" files. Installs from git would then mean having to also install "yarn" and run "yarn install && grunt". And this step should also be in the script for the zip archive.

### Advantages

Makes the code cleaner by using a library for common things. Right now it's pretty basic (only used once in the code), but in the future the same library (http-foundation) can be used for more (file uploads, session handing, get/post stuff). This library is has "foundation" in the name for a reason: it deals with basic stuff so you don't have to deal with it. Also, when doing `composer install`, composer will take care of checking the PHP version and the installed extensions. See the `composer.json` file.

PSR-4 autoloading: the classes (or just the class now) can be automatically loaded with the PSR-4 standard. So if one day you decide to expand the capabilities of the software, you can do so very easily by adding a class in the `src/classes` folder and it'll work immediatly.

### Disadvantages

Need a step to install the vendor dir. But this is common to ALL PHP apps, so not really something crazy to do ;)

## Assets

I moved the source files for JS and CSS to `src/js` and `src/css` as that's where one would expect to find them. The minified files are still generated in the `assets` folder.

## Namespacing

The software is in the Robiso\Wondercms namespace. This is good practice, it makes the wcms code encapsulated in its world.

## Static analysis

Now that the codebase starts to look like something decent, static analyzers can be used to spot bugs. As I've mentionned before, I was able to suppress almost all errors and warnings given by different tools. I recommend creating an account on scrutinizer-ci.com and setting up automated analysis on the `dev` branch. It's really useful, you'll see. It helps catch bugs that are obvious for a software, much less for a human. Automated testing is really something great to have. We're still far from it but at least now there is the basis for getting there. Before it was just impossible. ([example](https://circleci.com/gh/elabftw/elabftw/tree/hypernext))

The `psalm.xml` file is the configuration file for `psalm`, a must have tool. Ideally, new contributions to the code should not increase the number of errors found by `psalm` or `phpstan` or `phpcs` etc...

## General changes

It's hard to tell about all the little things that I changed because of the file move, the git diff is not very useful. But for instance, the backup code.

The function needed to be called with a source and destination. But the arguments were always the same. So I moved all the logic inside the function. So one just needs to call it and not have to think about anything else. It's always better to have functions without arguments. Look at the [before](https://github.com/robiso/wondercms/blob/dev/index.php#L1041-L1068) and [after](https://github.com/NicolasCARPi/wondercms/blob/next/src/classes/Wcms.php#L1099-L1122). See how it has less indentation? It's always better to aim for "flat" functions (without too much ifs and such). Also, error handing improved, see below (exceptions).

### Uniqid: 

uniqid() is deprecated (or will be) see https://wiki.php.net/rfc/deprecate-uniqid, so I replaced it with `random_bytes`, now that we are on PHP 7.1, we should use the better functions!

### Antislashes:

You'll see that some functions are called with an antislash in front of it. This is because PHP first tries to see if the function exists in the current namespace, before searching for it elsewhere. This instructs PHP to directly get it from the root namespace. It makes the generated bytecode faster. It's not really noticeable of course, like all the microoptimizations in PHP, but it's there.

### Exceptions:

You might see that some functions are throwing the generic `\Exception`. Throwing exception is very convenient. It allows to stop the code execution and to continue it in the "catch" block. So for instance if we go back to the zipBackup function: before, if there was an error, it was supposed to return false. But the code calling it was only doing something if the result was true, so if you had an error, there was no way to know what it was. Now the index.php file calls the functions in a try catch block, and can display the specific error to the user instead of failing silently. Again, I've just began with it, but in the future, having custom exceptions will be even better, you'll see (yes I'm teasing :p). Exceptions will allow a much cleaner a robust code, it really is the way to go when dealing with errors that should stop execution of the code. Right now the index.php file is just displaying the error, but we can think of having a generic error page, and display the error message on this page. For instance, the page not found error could be a `PageNotFoundException`, and the catch block would catch this specific exception and send the 404 status code and display the 404 error page. As you see, it allows a nice granular handling of errors. And this can be done very cleanly with the same `http-foundation` library. I've only added one dependency to the code, but it's a really useful one!

I think I'll stop here for the explanations. Please read the code and familiarize yourself with it. Once you get the "gist of it", you'll find that hacking on wondercms has become much more easier ;)

Also, at this point I think it would make sense to add me as a collaborator on this repo. I will not be able to push on the master branch, and I'll keep creating branches and making merge requests on the dev branch for you to review, but it'll save me from maintaining a fork ;)

Typing all of the above gave me strong incentive to continue improving Wcms (like adding custom exceptions). But I'll wait for you to accept these changes first, so we can get better commit diffs.

I wanted to make the PR before forgetting about all the changes I made two weeks ago…

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Ah also I move the db in the `data` folder. The goal will be to have the uploaded files here to, so the docker image can properly work with a normal volume folder (instead of the root folder). And it'll allow to have only this folder writeable by the server (and maybe the plugins folder too). This is better in term of security of the app. Note: this means a change to the configuration to prevent direct access to the db. 

As I said, there are still things to be done in terms of upgrading from v2 to v3 but each in its own time.

Note: you should squash the commits when merging so it all appears as one clean commit in the history of the dev branch.

**Comment by robiso** [comment]
Awesome changes @NicolasCARPi, kudos! 👏 🏆 
Thank you for the great comments and explanation. I welcome myself to the PHP of 2019!

Since you've basically rewritten the whole app in a "2019 way", I'll be adding you to the WonderCMS about page with the release of 3.0.0. Please count me in as your fan! :)

I'm more than happy to have you on board as a collaborator (added). Important note: please be careful not to push changes to the master branch (or the master version file), as that will initiate a "WonderCMS update" notification for users. Users who are updating today from 2.5.0 to 2.6.0 are still getting the files fetched from the master branch.

I also created the wondercms-builder and added you there also as a collaborator.

> I recommend creating an account on scrutinizer-ci.com and setting up automated analysis on the `dev` branch. It's really useful, you'll see. It helps catch bugs that are obvious for a software, much less for a human. Automated testing is really something great to have. We're still far from it but at least now there is the basis for getting there. Before it was just impossible.

Please let me know when the time has come for this and I will set up an account.

> Note: you should squash the commits when merging so it all appears as one clean commit in the history of the dev branch.

I don't think I've ever squashed before. Just to confirm, does that mean I check and accept them one by one instead of the whole batch of changes like usually?

> for the zip install, you will need to have a script generating a zip with all the required files in there, and that's the zip that users will download and put on their server for an out-of-the-box experience. Basically, the script will just install composer and run `composer install`, and create a zip, nothing complicated to do. Maybe create a "wondercms-builder" repo and add me as contributor, I'll add the script.

Is it possible to ask you for any additional instructions on this? I would like to test these changes as the end user (unzip and upload), and I'm not entirely sure what should be currently done. Where will this ZIP file be generated in the end? Will it be possible to continuously create ZIP files for each new version of WonderCMS for the "unzip and upload" functionality?
Let me know and I'll get to testing the 3.0.0 version and report back.

Bonus question:
Maybe it's to soon to ask, but how will the updating process work for users upgrading from 3.0.0 and onwards? I see the "updateAction" function still being present and has the index.php overwriting functionality, but in this case I guess it would be better to update the Wcms.php file instead of the index.php.

**Comment by robiso** [comment]
> Typing all of the above gave me strong incentive to continue improving Wcms (like adding custom exceptions). But I'll wait for you to accept these changes first, so we can get better commit diffs.

You're stuck with WonderCMS now! 😄

**Comment by NicolasCARPi** [comment]
> I don't think I've ever squashed before.

On the Merge pull request button, click the down arrow and select "Squash and merge".

> Is it possible to ask you for any additional instructions on this?

I'll add it to wondercms-builder repo.

> Where will this ZIP file be generated in the end?

On your server. But it could also be generated on a third party service (like travis-ci or something).

> Will it be possible to continuously create ZIP files for each new version of WonderCMS for the "unzip and upload" functionality?

Yes, even for each commit, with automated testing everytime. This is called CI (continuous integration).

> Maybe it's to soon to ask, but how will the updating process work for users upgrading from 3.0.0 and onwards? I see the "updateAction" function still being present and has the index.php overwriting functionality, but in this case I guess it would be better to update the Wcms.php file instead of the index.php. I would really, really like to retain some sort of update functionality for the novice users.

Yes, it'll need to be adapted to also get the newest version of the other needed files. But as I said before, even if I agree that having this functionality is nice, it might prove tricky to implement. Imagine there is a new file to download: old code won't know about it. A workaround would be to fetch a file with the necessary files to download (and their sha1sum), so something like a manifest file, and get them and replace them on the server. This would also allow proper handling of the update process, with error throwing if there was an issue downloading a file (shit happens). Note that this update process means that ALL files need to be writeable by the server process. Something that can be considered bad practice. But if you chose to keep this functionality, it can be implemented easily. I'm thinking, the code could even download the latest version as zip, and unpack it itself, instead of having to maintain a list of files, it would just get the latest "built" zip from wondercms.com/latest.zip and unpack the files, that is better!

**Comment by NicolasCARPi** [comment]
> You're stuck with WonderCMS now!

That's ok, it's quite enjoyable to hack on it :)

**Comment by robiso** [comment]
> I'm thinking, the code could even download the latest version as zip, and unpack it itself, instead of having to maintain a list of files, it would just get the latest "built" zip from wondercms.com/latest.zip and unpack the files, that is better!

This sounds justifiable and absolutely brilliant!

> Note that it would be nice also to remove the minified files (js and css) from git

I've seem to forgot to reply to this, do you want me to remove the minified files on the dev branch? Is there any way I can give you additional access to remove the files you deem necessary?

Thanks for all the answers, squashed away. 👍 
/nightowl reporting out, thanks again for investing yourself on this project!
Please let me know if there's any services I can sign up for immediately if they make your(our) lives easier.

**Comment by NicolasCARPi** [comment]
>  do you want me to remove the minified files on the dev branch?

Nah I'll do it in the next PR.

> Please let me know if there's any services I can sign up for immediately

I think you can start with scrutinizer-ci.com. https://insight.symfony.com/ is also good.

**Comment by robiso** [comment]
@NicolasCARPi, is circle-ci any different than any of those you've mentioned in terms of functionality?

**Comment by NicolasCARPi** [comment]
Yeah, it's a bit different. I'd say starting with scrutinizer is great because it runs code analysis + the tests, on each commit. Circle-ci requires a bit more configuration, and would not be useful right now as there are no tests.

**Comment by NicolasCARPi** [comment]
BTW: I've created the build script: https://github.com/robiso/wondercms-builder

It only takes the necessary files after "building" them.

The next steps would be to git clone the repo on your server, and install a webhook so that each commit on dev branch creates a latest-dev.zip and each commit on master branch creates a latest.zip archive. What I just said needs some adjustements to the script because right now it's only taking from the dev branch.

**Comment by robiso** [comment]
@NicolasCARPi, signed up with scrutinizer. I've also sent it to your email in case you need to use this for your personal projects. I set the dev branch as the main one, is that ok?

I've already tried to create a pull request for a couple patches (just some spaces).
The is one more huge spacing change, but didn't seem necessary and I'll leave the choice up to you, the original scrutinizer. :)

Once we've got everything ready, I would suggest switching over to Travis or Circle CI if possible, they seem cheaper and more popular (https://stackshare.io/stackups/circleci-vs-scrutinizer-vs-travis-ci), albeit scrutinizer seems really easy.

> The next steps would be to git clone the repo on your server, and install a webhook so that each commit on dev branch creates a latest-dev.zip and each commit on master branch creates a latest.zip archive. What I just said needs some adjustements to the script because right now it's only taking from the dev branch.

I might need some of your help with this when/if you'll have the time.

**Comment by NicolasCARPi** [comment]
scrutinizer is free for open source projects, so don't worry about pricing! But I see you merged a patch that changed all spaces back to tabs!!! You might want to revert that!

**Comment by robiso** [comment]
@NicolasCARPi, I noticed in the settings it was set to tab indentation, I've changed it to spaces to keep up to the defined standards.

No suggested changes coming from scrutinizer any more!

**Comment by NicolasCARPi** [comment]
Also, I see you removed the concatenation spaces. It's a matter of taste but I think it's more readable with spaces around it.

Here is my scrutinizer config:

~~~yml
filter:
    excluded_paths:
        - 'vendor/*'
checks:
    php:
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        no_goto: true
        more_specific_types_in_doc_comments: true
        fix_line_ending: true
        symfony_request_injection: false
        no_exit: false
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    environment:
        php:
            version: 7.1
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: phpcs-run
                        use_website_config: true
                    - php-scrutinizer-run

~~~

Oh I see I have access to the settings from scrutinizer-ci. But I'll let you change that.

**Comment by robiso** [comment]
Seems like the order of your config is different than mine. Can you post your whole config?

**Comment by NicolasCARPi** [comment]
The order is not really important, only the indentation. Here is the full config:

~~~yml
filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
checks:
    php:
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        no_goto: true
        more_specific_types_in_doc_comments: true
        fix_line_ending: true
        symfony_request_injection: false
        no_exit: false
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    environment:
        php:
            version: 7.1
    tests:
        before:
            - 'true;#sed -ie "s/BeUsed = \[\]/BeUsed = \[\], \$ignoreForceCoversAnnotation = false/" /home/scrutinizer/build/vendor/codeception/codeception/src/Codeception/Coverage/DummyCodeCoverage.php'
        override:
            -
                command: 'vendor/codeception/codeception/codecept run --skip acceptance --coverage --coverage-xml'
                coverage:
                    file: 'tests/_output/coverage.xml'
                    format: 'clover'
    dependencies:
        before:
            - mysql -uroot -e "create database phpunit;"
            - mysql -uroot phpunit < src/sql/structure.sql
            - mysql -uroot phpunit < tests/_data/phpunit.sql
            - sudo apt-get update
            - sudo apt-get install -y graphicsmagick-libmagick-dev-compat
            - yes|pecl install gmagick-2.0.4RC1
            - nvm use stable
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: phpcs-run
                        use_website_config: true
                    - php-scrutinizer-run
~~~

**Comment by robiso** [comment]
Saved and re-running. Hope this fixes the tabs. :)

**Comment by robiso** [comment]
@NicolasCARPi, as far as I can tell, there are no more tabs and the concatenation is back.
Cheers. 🎉

**Comment by NicolasCARPi** [comment]
Yep, I was able to make the PR on exceptions :)

**Comment by robiso** [comment]
@NicolasCARPi, would you please share some instructions on how I can give the latest dev version a test spin on my server? :)

**Comment by NicolasCARPi** [comment]
@robiso If you just git clone the dev branch, create a data folder with permissions for the server user to write to it, it should be enough.

**Comment by robiso** [comment]
@NicolasCARPi, managed to get it working (I was also missing composer).

Will get to fixing the plugins, thanks for the help, once again!

**Comment by robiso** [comment]
@NicolasCARPi, noticed an issue in Settings->General when moving a page "up" or "down" in a menu, it overwrites the values.

For example, we have 2 pages:
- Home
- Example
When I click "up" (to move the Example page above Home), both pages become Example.

**Comment by robiso** [comment]
@NicolasCARPi, to keep you posted:
1. I'm almost half way done with all the themes.
2. I've created a simple kanban board: https://github.com/robiso/wondercms/projects/3 (let me know if you'd like to add anything).

**Pull request merged**
