### PR TITLE
Update Wcms.php

### PR DESCRIPTION
**Pull request by robiso**
- Minor comments copy changes.
- Moved themes and plugins to the data directory.
- Fixed 404 pages and visiting /logout throwing errors (removed array declaration in notFoundView also added isset for the token check to avoid the error).
- Uncommented the plugin loading, as the Summernote editor works now (will be uploaded shortly).

### CODE REVIEW

**Comment by notcarbide** [comment]
Builds from devFixes do not work.

The folders themselves have yet to be moved into the data directory

**Comment by robiso** [comment]
@notcarbide thanks, files have been moved. 👍

**Comment by notcarbide** [comment]
Are they in the right directory? The code and comments imply that it should be in `data` rather than `assets`

**Comment by robiso** [comment]
🤦‍♂️ (double facepalm). Will fix it when I get home.
Thanks again @notcarbide.

**Comment by robiso** [comment]
Should be fine now. All this folder "restructuring" got me thinking if "data" is the correct folder for these themes and plugins, since they don't contain any user generated data.

When the update functionality is going to be implemented, all the files will be overwritten, except the data folder, which will contain the users database.js and their respective uploaded files.

Does it make sense to mix the two?
- possibly if the user has made a custom theme?

If getting the sense that this two should be probably separated (as they were before).

What do you guys think? @NicolasCARPi @notcarbide

**Comment by notcarbide** [comment]
I agree that data probably isn't the best place for them unless they are user downloaded/custom themes or plugins.

**Comment by robiso** [comment]
@notcarbide @NicolasCARPi would it still be possible to preserve custom themes and plugins if they are outside the data folder (when using the future "one click update")?

That's why my initial thought was to get them to the data folder and always preserve them, while we can still preform updates to those themes/plugins (through the URL to ZIP functionality).

**Comment by NicolasCARPi** [comment]
The idea is that the `data` folder is only for the user generated content. All else should ship with the release.

**Pull request merged**
