### PR TITLE
Non-standard HTTP port support

### PR DESCRIPTION
**Pull request by gakowalski**
Also: added gitignore and simple fix for PHP warning

### CODE REVIEW

**Comment by robiso** [comment]
@gakowalski thank you for your contribution. Can you please paste the warning you got, before the fix?

**Comment by gakowalski** [comment]
I'll try to summarize it quickly.

### Warning

Actually, it was a notice: `Notice: Undefined variable: scripts in C:\IT\GitHub\wondercms\index.php on line 193`. It's about the last line of this code:

```php
public static function js() {
  if (wCMS::$loggedIn) {
    $scripts = '<script>var token = "'.wCMS::_generateToken().'";</script>';
    /* ... */
  }
  return wCMS::_hook('js', $scripts)[0];
}
```

If user is not logged in, `$scripts` is undefined. Hence the notice. What I did:

```php
public static function js() {
  if (wCMS::$loggedIn) {
    $scripts = '<script>var token = "'.wCMS::_generateToken().'";</script>';
    /* ... */
    return wCMS::_hook('js', $scripts)[0];
  }
  return wCMS::_hook('js', '')[0];
}
```

Now if user is not logged in, an empty string is returned.

### Non-standard HTTP port support

When I tried to run wondercms on non-standard port 8000 I've noticed that port number is missing in links generated by `wCMS::url()`:

```php
public static function url($location = '') {
  return 
    'http' 
    . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on' ? 's' : '') 
    . '://' 
    . $_SERVER['SERVER_NAME']
/* no port number here! */
    .((dirname($_SERVER['SCRIPT_NAME']) == '/')? '' : dirname($_SERVER['SCRIPT_NAME'])) 
    . '/' 
    . $location;
}
```
 so I added `(($_SERVER['SERVER_PORT'] == '80')? '' : ':'.$_SERVER['SERVER_PORT'])` into proper place in the code.

**Comment by gakowalski** [comment]
### .gitignore
Added rule to ignore 'database.js' as it's generated dynamically and shouldn't be part of a commit.

**Comment by robiso** [comment]
Thank you for taking the time for explaining.

Would you mind adding port 443 support to your pull request
`((($_SERVER['SERVER_PORT'] == '80') || ($_SERVER['SERVER_PORT'] == '443') )? '' : ':'.$_SERVER['SERVER_PORT'])`

Once this gets accepted, we would also like to publicly credit you along side your website on our channels. Mind sharing your name/website?

**Comment by gakowalski** [comment]
I just added port 443 support to the pull request.

My name and website: Grzegorz Kowalski, [www.grzegorzkowalski.pl](http://www.grzegorzkowalski.pl).

**Comment by robiso** [comment]
@gakowalski we've successfully merged your pull request and pushed out WonderCMS 2.2.1 with some other minor fixes.

We have publicly credited you at the following links:
https://www.wondercms.com/whatsnew
https://www.wondercms.com/special-contributors
https://www.wondercms.com/latest
https://www.wondercms.com/forum/viewtopic.php?f=8&t=892
https://github.com/robiso/wondercms - readme
https://github.com/robiso/wondercms/releases in the release notes

**Comment by gakowalski** [comment]
Thank you! That's very encouraging!

**Comment by robiso** [comment]
You're most welcome, thanks for contributing!

**Pull request merged**
